### PR TITLE
overhaul of Instagram-Bot

### PR DESCRIPTION
**Pull request by decentral1se**
I used your original version as a base for a script I wrote for a contract. I decided to refactor the code and here is what I got in the end.

I also added a 'maxlike' in which the script will sleep to avoid instagram rate limiting.

I have no real idea what those regexs are really doing, so they are here to stay it seems, other than that, I think it is definitely more readable.

Cheers, 
Luke

### CODE REVIEW

**Comment by decentral1se** [comment]
also, I have tested this and it still works as before.

**Comment by Katazui** [comment]
How is the config.txt supposed to look like?

**Comment by decentral1se** [comment]
woops, forgot to mention, simply a text file with each hashtag on a seperate line. See image below...

Works out much easier to add on hashtags to the script.

configtxt

**Comment by rheinmetal** [comment]
i keep getting syntax error and i cant find the error, any knowledge?

**Pull request closed without merging**
